### ISSUE TITLE
Dribbble API for Java.

### ISSUE THREAD

**Issue by mthli** [dribbble/api-documentation#22]
Hi there, I wrote a Dribbble API for Java library, simple and crude. 
You can visit this at [Dribbble4J](https://github.com/mthli/Dribbble4J "Dribbble4J")
Hope can help you :)

**Comment by pbyrne** [comment]
Thanks for building an API client!

**Comment by frogandcode** [comment]
BTW we hope to pull together a page of API applications and libraries at some point, we'll add this to the list when the time comes. Thanks so much for creating it!
