### ISSUE TITLE
Field in shot response to indicate if image is GIF

### ISSUE THREAD

**Issue by rounak** [dribbble/api-documentation#23]
I used the .gif extension at the end of a URL as an indicator of whether a shot image is a GIF or not. But I've encountered a few cases where the URL had no .gif extension and the image was a GIF.

I was wondering if you could have an indicator or maybe a image file type in the shot response. The thing is on iOS GIF support isn't native, so I have to add some checks and travel a different code path if the image is a GIF.

**Comment by pbyrne** [comment]
> But I've encountered a few cases where the URL had no .gif extension and the image was a GIF. I was wondering if you could have an indicator or maybe a image file type in the shot response.

It's probably safest to look at the `Content-Type` header when downloading the image to determine whether it's a GIF. GIFs will have a value of `image/gif`. It's possible that players have uploaded shots with no file extension or with the wrong file extension, which it seems you might be running into. Do you have any example shots which didn't have the `.gif` extension you can share? I can dig in a bit deeper to see if there's some kind of problem.

> The thing is on iOS GIF support isn't native, so I have to add some checks and travel a different code path if the image is a GIF.

Would you mind going into a bit more detail on that? Understanding your use case here could help us make the best choices moving forward with the API.

**Comment by rounak** [comment]
> It's probably safest to look at the Content-Type header when downloading the image to determine whether it's a GIF. GIFs will have a value of image/gif.

Got it. 

> Do you have any example shots which didn't have the .gif extension you can share?

https://dribbble.com/shots/1985467-Dusk?list=following&offset=7

> Would you mind going into a bit more detail on that

UIImageView (the default image container on iOS) doesn't support GIFs out of the box. So typically everyone uses a third party library like [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage) to get GIFs to animate. So in my case I check if the URL has .gif, if so, I create an instance of `FLAnimatedImage`, else I let the system do its thing to get the image on screen. I don't think this relates much to the Dribbble API, though. 

As you said, I'll use the downloaded image's content type instead, and everything should work fine.

**Comment by pbyrne** [comment]
:+1:
