### ISSUE TITLE
Testing authenticated responses to `/user/shots`

### ISSUE THREAD

**Issue by jimmed** [dribbble/api-documentation#25]
I'm not sure if this is the correct place to ask this, so feel free to shoot it down.

I'm involved in developing an app which allows grabbing a user's Dribbble shots using their oAuth access token. Implementing and testing authentication via oAuth was straightforward.

Annoyingly, because I don't know anybody who has a 'player' account (i.e. who can upload shots), I cannot test the part of the app which retrieves the currently authenticated user's shots.

The Dribbble API documentation is sufficient that I can mostly prove that my code will work, but I won't know for sure until a Dribbble 'player' comes along and uses my app.

How can I test this properly?

**Comment by frogandcode** [comment]
I'm gonna close this out since since it doesn't regard the API docs per se, but if you can sign in to your Dribbble account (so we know who you are) and send us a support request here:

https://dribbble.com/contact

I can hook you up with a solution.

Cheers,
Rich
