### ISSUE TITLE
Hostname in certificate didn't match, apache http library

### ISSUE THREAD

**Issue by Dannemannet** [dribbble/api-documentation#33]
When trying to access the API from android devices using the built in apache http library I get an exception saying:
hostname in certificate didn't match: <api.dribbble.com> != <dribbble.com> OR <dribbble.com> OR <www.dribbble.com>

This is the code that fail to execute:

	DefaultHttpClient httpclient = new DefaultHttpClient();
   	HttpGet httpGet = new HttpGet("https://api.dribbble.com/v1/user");
	httpGet.setHeader("Authorization",	"Bearer " + ACCESS_TOKEN);
	HttpResponse response = httpclient.execute(httpGet);

It seems to be a problem with the SSL certificate, that dribbble doesn't have a certificate for the host api.dribbble.com, only dribbble.com which explains why the OAuth process works when it uses that endpoint.

I've read that a hack fix could be to allow all verifiers, but this would make the communication unsafe. Is there another solution for this?

**Comment by frogandcode** [comment]
We spoke offline via the Dribbble support email, looks like this was an issue with the library being used, not the API itself, so closing.
